#!/bin/bash

#./X53Analyzer.o ChargeMisIDElEl2016B  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElMu2016B  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElEl2016C  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElMu2016C  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElEl2016D  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElMu2016D  MVATightMedIsoRC CBTightMiniIso;
#./X53Analyzer.o ChargeMisIDElEl2016E  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElMu2016E  MVATightMedIsoRC CBTightMiniIso&
./X53Analyzer.o ChargeMisIDElEl2016F  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElMu2016F  MVATightMedIsoRC CBTightMiniIso;
./X53Analyzer.o ChargeMisIDElEl2016G  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElMu2016G  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElEl2016H2  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElMu2016H2  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElEl2016H3  MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o ChargeMisIDElMu2016H3  MVATightMedIsoRC CBTightMiniIso&

#./X53Analyzer.o NonPromptDataElEl2016B MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElMu2016B MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataMuMu2016B MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElEl2016C MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElMu2016C MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataMuMu2016C MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElEl2016D MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElMu2016D MVATightMedIsoRC CBTightMiniIso;
#./X53Analyzer.o NonPromptDataMuMu2016D MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElEl2016E MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElMu2016E MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataMuMu2016E MVATightMedIsoRC CBTightMiniIso&
./X53Analyzer.o NonPromptDataElEl2016F MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElMu2016F MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataMuMu2016F MVATightMedIsoRC CBTightMiniIso;
./X53Analyzer.o NonPromptDataElEl2016G MVATightMedIsoRC CBTightMiniIso;
#./X53Analyzer.o NonPromptDataElMu2016G MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataMuMu2016G MVATightMedIsoRC CBTightMiniIso;
#./X53Analyzer.o NonPromptDataElEl2016H2 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElMu2016H2 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataMuMu2016H2 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElEl2016H3 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataElMu2016H3 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o NonPromptDataMuMu2016H3 MVATightMedIsoRC CBTightMiniIso;


#./X53Analyzer.o DataElEl2016B MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElMu2016B MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataMuMu2016B MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElEl2016C MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElMu2016C MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataMuMu2016C MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElEl2016D MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElMu2016D MVATightMedIsoRC CBTightMiniIso;
#./X53Analyzer.o DataMuMu2016D MVATightMedIsoRC CBTightMiniIso;
#./X53Analyzer.o DataElEl2016E MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElMu2016E MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataMuMu2016E MVATightMedIsoRC CBTightMiniIso&
./X53Analyzer.o DataElEl2016F MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElMu2016F MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataMuMu2016F MVATightMedIsoRC CBTightMiniIso;
./X53Analyzer.o DataElEl2016G MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElMu2016G MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataMuMu2016G MVATightMedIsoRC CBTightMiniIso;
#./X53Analyzer.o DataElEl2016H2 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElMu2016H2 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataMuMu2016H2 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElEl2016H3 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataElMu2016H3 MVATightMedIsoRC CBTightMiniIso&
#./X53Analyzer.o DataMuMu2016H3 MVATightMedIsoRC CBTightMiniIso;